/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as DecksRouteImport } from './routes/decks'
import { Route as GroepenRouteImport } from './routes/groepen'
import { Route as InstellingenRouteImport } from './routes/instellingen'
import { Route as LessenRouteImport } from './routes/lessen'
import { Route as NotitiesRouteImport } from './routes/notities'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as StatistiekenRouteImport } from './routes/statistieken'
import { Route as CijfersIndexRouteImport } from './routes/cijfers.index'
import { Route as CijfersSubjectRouteImport } from './routes/cijfers.$subject'
import { Route as VakkenIndexRouteImport } from './routes/vakken.index'
import { Route as VakkenSplatRouteImport } from './routes/vakken.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksRoute = DecksRouteImport.update({
  id: '/decks',
  path: '/decks',
  getParentRoute: () => rootRouteImport,
} as any)
const GroepenRoute = GroepenRouteImport.update({
  id: '/groepen',
  path: '/groepen',
  getParentRoute: () => rootRouteImport,
} as any)
const InstellingenRoute = InstellingenRouteImport.update({
  id: '/instellingen',
  path: '/instellingen',
  getParentRoute: () => rootRouteImport,
} as any)
const LessenRoute = LessenRouteImport.update({
  id: '/lessen',
  path: '/lessen',
  getParentRoute: () => rootRouteImport,
} as any)
const NotitiesRoute = NotitiesRouteImport.update({
  id: '/notities',
  path: '/notities',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const StatistiekenRoute = StatistiekenRouteImport.update({
  id: '/statistieken',
  path: '/statistieken',
  getParentRoute: () => rootRouteImport,
} as any)
const CijfersIndexRoute = CijfersIndexRouteImport.update({
  id: '/cijfers/',
  path: '/cijfers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CijfersSubjectRoute = CijfersSubjectRouteImport.update({
  id: '/cijfers/$subject',
  path: '/cijfers/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const VakkenIndexRoute = VakkenIndexRouteImport.update({
  id: '/vakken/',
  path: '/vakken/',
  getParentRoute: () => rootRouteImport,
} as any)
const VakkenSplatRoute = VakkenSplatRouteImport.update({
  id: '/vakken/$',
  path: '/vakken/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/decks': typeof DecksRoute
  '/groepen': typeof GroepenRoute
  '/instellingen': typeof InstellingenRoute
  '/lessen': typeof LessenRoute
  '/notities': typeof NotitiesRoute
  '/planner': typeof PlannerRoute
  '/statistieken': typeof StatistiekenRoute
  '/cijfers/$subject': typeof CijfersSubjectRoute
  '/vakken/$': typeof VakkenSplatRoute
  '/cijfers/': typeof CijfersIndexRoute
  '/vakken/': typeof VakkenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/decks': typeof DecksRoute
  '/groepen': typeof GroepenRoute
  '/instellingen': typeof InstellingenRoute
  '/lessen': typeof LessenRoute
  '/notities': typeof NotitiesRoute
  '/planner': typeof PlannerRoute
  '/statistieken': typeof StatistiekenRoute
  '/cijfers/$subject': typeof CijfersSubjectRoute
  '/vakken/$': typeof VakkenSplatRoute
  '/cijfers': typeof CijfersIndexRoute
  '/vakken': typeof VakkenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/decks': typeof DecksRoute
  '/groepen': typeof GroepenRoute
  '/instellingen': typeof InstellingenRoute
  '/lessen': typeof LessenRoute
  '/notities': typeof NotitiesRoute
  '/planner': typeof PlannerRoute
  '/statistieken': typeof StatistiekenRoute
  '/cijfers/$subject': typeof CijfersSubjectRoute
  '/vakken/$': typeof VakkenSplatRoute
  '/cijfers/': typeof CijfersIndexRoute
  '/vakken/': typeof VakkenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/decks'
    | '/groepen'
    | '/instellingen'
    | '/lessen'
    | '/notities'
    | '/planner'
    | '/statistieken'
    | '/cijfers/$subject'
    | '/vakken/$'
    | '/cijfers/'
    | '/vakken/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/decks'
    | '/groepen'
    | '/instellingen'
    | '/lessen'
    | '/notities'
    | '/planner'
    | '/statistieken'
    | '/cijfers/$subject'
    | '/vakken/$'
    | '/cijfers'
    | '/vakken'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/decks'
    | '/groepen'
    | '/instellingen'
    | '/lessen'
    | '/notities'
    | '/planner'
    | '/statistieken'
    | '/cijfers/$subject'
    | '/vakken/$'
    | '/cijfers/'
    | '/vakken/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  DecksRoute: typeof DecksRoute
  GroepenRoute: typeof GroepenRoute
  InstellingenRoute: typeof InstellingenRoute
  LessenRoute: typeof LessenRoute
  NotitiesRoute: typeof NotitiesRoute
  PlannerRoute: typeof PlannerRoute
  StatistiekenRoute: typeof StatistiekenRoute
  CijfersSubjectRoute: typeof CijfersSubjectRoute
  VakkenSplatRoute: typeof VakkenSplatRoute
  CijfersIndexRoute: typeof CijfersIndexRoute
  VakkenIndexRoute: typeof VakkenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks': {
      id: '/decks'
      path: '/decks'
      fullPath: '/decks'
      preLoaderRoute: typeof DecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groepen': {
      id: '/groepen'
      path: '/groepen'
      fullPath: '/groepen'
      preLoaderRoute: typeof GroepenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instellingen': {
      id: '/instellingen'
      path: '/instellingen'
      fullPath: '/instellingen'
      preLoaderRoute: typeof InstellingenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessen': {
      id: '/lessen'
      path: '/lessen'
      fullPath: '/lessen'
      preLoaderRoute: typeof LessenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notities': {
      id: '/notities'
      path: '/notities'
      fullPath: '/notities'
      preLoaderRoute: typeof NotitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistieken': {
      id: '/statistieken'
      path: '/statistieken'
      fullPath: '/statistieken'
      preLoaderRoute: typeof StatistiekenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cijfers/': {
      id: '/cijfers/'
      path: '/cijfers'
      fullPath: '/cijfers/'
      preLoaderRoute: typeof CijfersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cijfers/$subject': {
      id: '/cijfers/$subject'
      path: '/cijfers/$subject'
      fullPath: '/cijfers/$subject'
      preLoaderRoute: typeof CijfersSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vakken/': {
      id: '/vakken/'
      path: '/vakken'
      fullPath: '/vakken/'
      preLoaderRoute: typeof VakkenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vakken/$': {
      id: '/vakken/$'
      path: '/vakken/$'
      fullPath: '/vakken/$'
      preLoaderRoute: typeof VakkenSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  DecksRoute: DecksRoute,
  GroepenRoute: GroepenRoute,
  InstellingenRoute: InstellingenRoute,
  LessenRoute: LessenRoute,
  NotitiesRoute: NotitiesRoute,
  PlannerRoute: PlannerRoute,
  StatistiekenRoute: StatistiekenRoute,
  CijfersSubjectRoute: CijfersSubjectRoute,
  VakkenSplatRoute: VakkenSplatRoute,
  CijfersIndexRoute: CijfersIndexRoute,
  VakkenIndexRoute: VakkenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
