/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroepenRouteImport } from './routes/groepen'
import { Route as KalenderRouteImport } from './routes/kalender'
import { Route as LessenRouteImport } from './routes/lessen'
import { Route as VakkenIndexRouteImport } from './routes/vakken.index'
import { Route as VakkenSplatRouteImport } from './routes/vakken.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroepenRoute = GroepenRouteImport.update({
  id: '/groepen',
  path: '/groepen',
  getParentRoute: () => rootRouteImport,
} as any)
const KalenderRoute = KalenderRouteImport.update({
  id: '/kalender',
  path: '/kalender',
  getParentRoute: () => rootRouteImport,
} as any)
const LessenRoute = LessenRouteImport.update({
  id: '/lessen',
  path: '/lessen',
  getParentRoute: () => rootRouteImport,
} as any)
const VakkenIndexRoute = VakkenIndexRouteImport.update({
  id: '/vakken/',
  path: '/vakken/',
  getParentRoute: () => rootRouteImport,
} as any)
const VakkenSplatRoute = VakkenSplatRouteImport.update({
  id: '/vakken/$',
  path: '/vakken/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/groepen': typeof GroepenRoute
  '/kalender': typeof KalenderRoute
  '/lessen': typeof LessenRoute
  '/vakken/$': typeof VakkenSplatRoute
  '/vakken/': typeof VakkenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/groepen': typeof GroepenRoute
  '/kalender': typeof KalenderRoute
  '/lessen': typeof LessenRoute
  '/vakken/$': typeof VakkenSplatRoute
  '/vakken': typeof VakkenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/groepen': typeof GroepenRoute
  '/kalender': typeof KalenderRoute
  '/lessen': typeof LessenRoute
  '/vakken/$': typeof VakkenSplatRoute
  '/vakken/': typeof VakkenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/groepen' | '/kalender' | '/lessen' | '/vakken/$' | '/vakken/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/groepen' | '/kalender' | '/lessen' | '/vakken/$' | '/vakken'
  id:
    | '__root__'
    | '/'
    | '/groepen'
    | '/kalender'
    | '/lessen'
    | '/vakken/$'
    | '/vakken/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GroepenRoute: typeof GroepenRoute
  KalenderRoute: typeof KalenderRoute
  LessenRoute: typeof LessenRoute
  VakkenSplatRoute: typeof VakkenSplatRoute
  VakkenIndexRoute: typeof VakkenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groepen': {
      id: '/groepen'
      path: '/groepen'
      fullPath: '/groepen'
      preLoaderRoute: typeof GroepenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalender': {
      id: '/kalender'
      path: '/kalender'
      fullPath: '/kalender'
      preLoaderRoute: typeof KalenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessen': {
      id: '/lessen'
      path: '/lessen'
      fullPath: '/lessen'
      preLoaderRoute: typeof LessenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vakken/': {
      id: '/vakken/'
      path: '/vakken'
      fullPath: '/vakken/'
      preLoaderRoute: typeof VakkenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vakken/$': {
      id: '/vakken/$'
      path: '/vakken/$'
      fullPath: '/vakken/$'
      preLoaderRoute: typeof VakkenSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GroepenRoute: GroepenRoute,
  KalenderRoute: KalenderRoute,
  LessenRoute: LessenRoute,
  VakkenSplatRoute: VakkenSplatRoute,
  VakkenIndexRoute: VakkenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
