-- Update study_sets table to support Artisan AI results
-- Adds fields for summary, quizzes, and other AI-generated content

ALTER TABLE public.study_sets
  ADD COLUMN IF NOT EXISTS is_artisan_generated BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS artisan_summary TEXT,
  ADD COLUMN IF NOT EXISTS artisan_quizzes JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS artisan_source_file TEXT,
  ADD COLUMN IF NOT EXISTS artisan_queue_id UUID REFERENCES public.artisan_queue(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS artisan_generated_at TIMESTAMPTZ;

-- Index for artisan-generated sets
CREATE INDEX IF NOT EXISTS idx_study_sets_is_artisan ON public.study_sets(is_artisan_generated) WHERE is_artisan_generated = TRUE;
CREATE INDEX IF NOT EXISTS idx_study_sets_artisan_queue ON public.study_sets(artisan_queue_id);

-- Add comment
COMMENT ON COLUMN public.study_sets.is_artisan_generated IS 'Whether this set was generated by Artisan AI';
COMMENT ON COLUMN public.study_sets.artisan_summary IS 'AI-generated summary of the source material';
COMMENT ON COLUMN public.study_sets.artisan_quizzes IS 'AI-generated quiz questions and answers';
COMMENT ON COLUMN public.study_sets.artisan_source_file IS 'Original source file name';
COMMENT ON COLUMN public.study_sets.artisan_queue_id IS 'Reference to the artisan queue entry';
COMMENT ON COLUMN public.study_sets.artisan_generated_at IS 'When the AI generation was completed';

-- Ensure is_public column exists (it should from original schema)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'study_sets' AND column_name = 'is_public'
  ) THEN
    ALTER TABLE public.study_sets ADD COLUMN is_public BOOLEAN DEFAULT FALSE;
  END IF;
END $$;

