// School OS Template - Dutch Secondary Education System
// Structure: Inbox, Taken, Vakken, Foutenlogboek, Herhaal Queue, Toetsen & Deadlines, Projecten

export const schoolOsTemplate = {
  name: 'School OS 2026-2027',
  description: 'Complete study system for Dutch secondary school students',
  structure: {
    pages: [
      {
        id: 'inbox',
        name: 'Inbox',
        type: 'page',
        icon: '📥',
        children: [],
      },
      {
        id: 'taken',
        name: 'Taken',
        type: 'page',
        icon: '✅',
        children: [],
        databases: [
          {
            name: 'Taken Database',
            properties: [
              { name: 'Taak', type: 'text' },
              { name: 'Vak', type: 'select', options: ['Wiskunde', 'Natuurkunde', 'Scheikunde', 'Biologie', 'Nederlands', 'Frans', 'Engels', 'Informatica', 'Geschiedenis', 'Aardrijkskunde'] },
              { name: 'Type', type: 'select', options: ['Huiswerk', 'Toets', 'Project', 'Presentatie'] },
              { name: 'Deadline', type: 'date' },
              { name: 'Status', type: 'select', options: ['Niet begonnen', 'Bezig', 'Afgerond'] },
              { name: 'Prioriteit', type: 'select', options: ['Laag', 'Gemiddeld', 'Hoog', 'P1 Dringend'] },
              { name: 'Energie', type: 'select', options: ['Laag', 'Gemiddeld', 'Hoog'] },
              { name: 'Tijd', type: 'select', options: ['< 30min', '30-60min', '1-2 uur', '> 2 uur'] },
              { name: 'Toetsrelevant', type: 'checkbox' },
            ],
            views: [
              { name: 'Vandaag', type: 'table', filters: [{ property: 'Deadline', operator: 'is', value: 'today' }] },
              { name: 'Deze week', type: 'table', filters: [{ property: 'Deadline', operator: 'is', value: 'this_week' }] },
              { name: 'P1 Dringend', type: 'table', filters: [{ property: 'Prioriteit', operator: 'is', value: 'P1 Dringend' }] },
              { name: 'Toetsvoorbereiding', type: 'kanban', groupBy: 'Vak' },
              { name: 'Achterstand', type: 'table', filters: [{ property: 'Deadline', operator: 'before', value: 'today' }, { property: 'Status', operator: 'is_not', value: 'Afgerond' }] },
            ],
          },
        ],
      },
      {
        id: 'vakken',
        name: 'Vakken',
        type: 'page',
        icon: '📚',
        children: [
          {
            id: 'wiskunde-b',
            name: 'Wiskunde B',
            type: 'page',
            icon: '📐',
            children: [
              { id: 'wb-lopende', name: 'Lopende stof', type: 'page' },
              { id: 'wb-huiswerk', name: 'Huiswerk', type: 'page' },
              { id: 'wb-toetsen', name: 'Toetsen', type: 'page' },
              { id: 'wb-formules', name: 'Belangrijke formules/begrippen', type: 'page' },
              { id: 'wb-active-recall', name: 'Active recall vragen', type: 'page' },
              { id: 'wb-fouten', name: 'Foutenlogboek', type: 'page' },
              { id: 'wb-moeilijk', name: 'Moeilijke onderwerpen', type: 'page' },
              { id: 'wb-analyse', name: 'Laatste toetsanalyse', type: 'page' },
              { id: 'wb-vragen', name: 'Wat moet ik vragen aan docent?', type: 'page' },
            ],
          },
          {
            id: 'wiskunde-d',
            name: 'Wiskunde D',
            type: 'page',
            icon: '📊',
            children: Array(9).fill(null).map((_, i) => ({ id: `wd-${i}`, name: ['Lopende stof', 'Huiswerk', 'Toetsen', 'Formules', 'Active recall', 'Foutenlogboek', 'Moeilijk', 'Analyse', 'Vragen'][i], type: 'page' })),
          },
          {
            id: 'natuurkunde',
            name: 'Natuurkunde',
            type: 'page',
            icon: '⚛️',
            children: Array(9).fill(null).map((_, i) => ({ id: `nk-${i}`, name: ['Lopende stof', 'Huiswerk', 'Toetsen', 'Formules', 'Active recall', 'Foutenlogboek', 'Moeilijk', 'Analyse', 'Vragen'][i], type: 'page' })),
          },
          {
            id: 'scheikunde',
            name: 'Scheikunde',
            type: 'page',
            icon: '🧪',
            children: Array(9).fill(null).map((_, i) => ({ id: `sk-${i}`, name: ['Lopende stof', 'Huiswerk', 'Toetsen', 'Formules', 'Active recall', 'Foutenlogboek', 'Moeilijk', 'Analyse', 'Vragen'][i], type: 'page' })),
          },
          {
            id: 'biologie',
            name: 'Biologie',
            type: 'page',
            icon: '🧬',
            children: Array(9).fill(null).map((_, i) => ({ id: `bio-${i}`, name: ['Lopende stof', 'Huiswerk', 'Toetsen', 'Formules', 'Active recall', 'Foutenlogboek', 'Moeilijk', 'Analyse', 'Vragen'][i], type: 'page' })),
          },
          {
            id: 'nederlands',
            name: 'Nederlands',
            type: 'page',
            icon: '📖',
            children: Array(9).fill(null).map((_, i) => ({ id: `nl-${i}`, name: ['Lopende stof', 'Huiswerk', 'Toetsen', 'Formules', 'Active recall', 'Foutenlogboek', 'Moeilijk', 'Analyse', 'Vragen'][i], type: 'page' })),
          },
          {
            id: 'frans',
            name: 'Frans',
            type: 'page',
            icon: '🇫🇷',
            children: Array(9).fill(null).map((_, i) => ({ id: `fr-${i}`, name: ['Lopende stof', 'Huiswerk', 'Toetsen', 'Formules', 'Active recall', 'Foutenlogboek', 'Moeilijk', 'Analyse', 'Vragen'][i], type: 'page' })),
          },
          {
            id: 'engels',
            name: 'Cambridge Engels',
            type: 'page',
            icon: '🇬🇧',
            children: Array(9).fill(null).map((_, i) => ({ id: `en-${i}`, name: ['Lopende stof', 'Huiswerk', 'Toetsen', 'Formules', 'Active recall', 'Foutenlogboek', 'Moeilijk', 'Analyse', 'Vragen'][i], type: 'page' })),
          },
          {
            id: 'informatica',
            name: 'Informatica',
            type: 'page',
            icon: '💻',
            children: Array(9).fill(null).map((_, i) => ({ id: `inf-${i}`, name: ['Lopende stof', 'Huiswerk', 'Toetsen', 'Formules', 'Active recall', 'Foutenlogboek', 'Moeilijk', 'Analyse', 'Vragen'][i], type: 'page' })),
          },
          {
            id: 'arabisch',
            name: 'Arabisch/Islamitisch',
            type: 'page',
            icon: '🕌',
            children: Array(9).fill(null).map((_, i) => ({ id: `ar-${i}`, name: ['Lopende stof', 'Huiswerk', 'Toetsen', 'Formules', 'Active recall', 'Foutenlogboek', 'Moeilijk', 'Analyse', 'Vragen'][i], type: 'page' })),
          },
        ],
      },
      {
        id: 'foutenlogboek',
        name: 'Foutenlogboek',
        type: 'page',
        icon: '📝',
        children: [],
        databases: [
          {
            name: 'Fouten Database',
            properties: [
              { name: 'Datum', type: 'date' },
              { name: 'Vak', type: 'select' },
              { name: 'Onderwerp', type: 'text' },
              { name: 'Vraag/Opgave', type: 'text' },
              { name: 'Fouttype', type: 'select', options: ['Rekenfout', 'Conceptfout', 'Leesfout', 'Tijdsdruk', 'Onbekend'] },
              { name: 'Mijn fout', type: 'text' },
              { name: 'Correcte aanpak', type: 'text' },
              { name: 'Waarom deze fout?', type: 'text' },
              { name: 'Herhalen op', type: 'date' },
              { name: 'Status', type: 'select', options: ['Nieuw', 'In behandeling', 'Begrepen', 'Beheerst'] },
              { name: 'Toetsrelevant', type: 'checkbox' },
            ],
          },
        ],
      },
      {
        id: 'herhaal-queue',
        name: 'Herhaal Queue',
        type: 'page',
        icon: '🔄',
        children: [],
        databases: [
          {
            name: 'Herhaal Database',
            properties: [
              { name: 'Vraag', type: 'text' },
              { name: 'Vak', type: 'select' },
              { name: 'Onderwerp', type: 'text' },
              { name: 'Niveau', type: 'select', options: ['Basis', 'Gemiddeld', 'Geavanceerd'] },
              { name: 'Volgende herhaling', type: 'date' },
              { name: 'Status', type: 'select', options: ['Nieuw', 'Lerend', 'Herhalend', 'Beheerst'] },
              { name: 'Laatste score', type: 'select', options: ['0%', '25%', '50%', '75%', '100%'] },
              { name: 'Aantal herhalingen', type: 'number' },
            ],
          },
        ],
      },
      {
        id: 'toetsen-deadlines',
        name: 'Toetsen & Deadlines',
        type: 'page',
        icon: '📅',
        children: [],
        databases: [
          {
            name: 'Toetsen Database',
            properties: [
              { name: 'Toets/Deadline', type: 'text' },
              { name: 'Vak', type: 'select' },
              { name: 'Datum', type: 'date' },
              { name: 'Hoofdstukken', type: 'text' },
              { name: 'Stof', type: 'text' },
              { name: 'Weging', type: 'number' },
              { name: 'Status', type: 'select', options: ['Gepland', 'Bezig', 'Afgerond'] },
              { name: 'Type', type: 'select', options: ['Toets', 'Tentamen', 'Presentatie', 'Huiswerk', 'Project'] },
              { name: 'T-7 Planning', type: 'text' },
              { name: 'T-3 Planning', type: 'text' },
              { name: 'T-1 Planning', type: 'text' },
            ],
            views: [
              { name: 'Komende week', type: 'calendar' },
              { name: 'Alle toetsen', type: 'table' },
            ],
          },
        ],
      },
      {
        id: 'projecten',
        name: 'Projecten',
        type: 'page',
        icon: '🎯',
        children: [],
        databases: [
          {
            name: 'Projecten Database',
            properties: [
              { name: 'Project', type: 'text' },
              { name: 'Vak', type: 'select' },
              { name: 'Deadline', type: 'date' },
              { name: 'Status', type: 'select', options: ['Idee', 'Planning', 'Uitvoering', 'Review', 'Afgerond'] },
              { name: 'Stappen', type: 'text' },
              { name: 'Afhankelijkheden', type: 'text' },
              { name: 'Opmerkingen', type: 'text' },
            ],
          },
        ],
      },
      {
        id: 'archief',
        name: 'Archief',
        type: 'page',
        icon: '🗄️',
        children: [],
      },
    ],
  },
};
